import { Metadata } from 'next'
import React from 'react'

export const metadata : Metadata = {
  title:"About me page",
  description:"Generated by next"

}

 const AboutMe = () => {
  return (
    <div>
      About Me
    </div>
  )
}

export default AboutMe